obsidian:
  vault_path: "/home/pimentel/Workspace/obsidian_vaults/personal-obsidian/Personal Vault"
  backup_path: "/home/pimentel/Documents/obsidian_backup"
  agenda_prefix: "1on1-"
  merged_notes_folder: "Merges"
  small_note_threshold: 100
  empty_note_threshold: 10
  archive_days_threshold: 180
  excluded_files:
    - "^\\..*" # Exclude hidden files and folders
    - "^_.*" # Exclude files and folders starting with underscore
    - "**/templates/**" # Exclude template folders anywhere in the vault
    - "**/Archive/**" # Exclude Archive folders anywhere in the vault
    - "**/Attachments/**" # Exclude Attachments folders anywhere in the vault
    - "**/.obsidian/**" # Exclude Obsidian config folders
    - "**/.trash/**" # Exclude Obsidian trash folders
    - "ignore_me.md"
    - "private_note.md"

smtp:
  server: "smtp.your-email-provider.com"
  port: 587
  username: "your-email@example.com"
  password: "your-email-password"
  from: "your-email@example.com"
  to: "recipient-email@example.com"

google_calendar:
  credentials_file: "credentials.json"
  token_file: "token.json"
